name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv (astral-sh)
        uses: astral-sh/setup-uv@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheel artifacts for workspace packages
        run: |
          python -m pip install --upgrade pip build
          mkdir -p .build
          for pkg in libs/sphere-core libs/sphere-data libs/sphere-flood; do
            (cd $pkg && python -m build -w -o ../../.build)
          done

      - name: Install built wheels
        run: |
          python -m pip install --upgrade pip
          python -m pip install ./.build/*.whl

      - name: Run tests
        run: |
          uv run pytest -q
