name: Release package

on:
  workflow_dispatch:
  push:
    tags:
      - 'sphere-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv (astral-sh)
        uses: astral-sh/setup-uv@v2
        with:
          python-version: '3.11'

      - name: Build wheels for package and workspace deps
        run: |
          uv build --all-packages

      - name: Run tests (uv)
        run: |
          uv run pytest -q

      - name: Build and upload (uv publish)
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          # publish using uv which handles upload and index settings
          uv publish --check-url https://pypi.org/simple/ --token "$UV_PUBLISH_TOKEN"   