name: TestPyPI Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'test-sphere-v*'

jobs:
  publish-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv (astral-sh)
        uses: astral-sh/setup-uv@v2
        with:
          python-version: '3.11'

      - name: Determine package dir
        id: pkg
        run: |
          TAG=${GITHUB_REF##refs/tags/}
          echo "tag=$TAG"
          # Single test tag triggers publishing of the meta-package at the repo root
          echo "pkg_dir=." >> $GITHUB_OUTPUT

      - name: Build wheels for package and workspace deps
        run: |
          uv build --all-packages

      - name: Run tests (uv)
        run: |
          uv run pytest -q

      - name: Build and upload to TestPyPI (uv publish)
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          uv publish --publish-url https://test.pypi.org/legacy/ --check-url https://test.pypi.org/simple --token "$UV_PUBLISH_TOKEN"